import { supabase } from './supabase.js';
import { state } from './state.js';
import { buildGrandmasterView, buildTraderDNA, sparklinePoints } from './grandmaster_core.js';

const clean = (value, max = 500) => String(value ?? '').replace(/[\u0000-\u001f\u007f]+/g, ' ').replace(/\s+/g, ' ').trim().slice(0, max);
const number = (value) => Number.isFinite(Number(value)) ? Number(value) : 0;
const list = (value) => Array.isArray(value) ? value.map((item) => clean(item, 300)).filter(Boolean) : [];
function money(value){const n=number(value);return `${n<0?'−':n>0?'+':''}$${Math.abs(n).toFixed(0)}`}
function renderSpark(id,values){const svg=document.getElementById(id);if(!svg)return;const points=sparklinePoints(values);svg.innerHTML=points?`<polyline points="${points}"></polyline><circle cx="${points.split(' ').at(-1).split(',')[0]}" cy="${points.split(' ').at(-1).split(',')[1]}" r="2.8"></circle>`:''}
function text(id,value){const el=document.getElementById(id);if(el)el.textContent=value}
function render(model){const latest=model.latest;text('gm-latest-date',latest?.trade_date||'NO REVIEW');text('gm-five-pnl',money(model.pnl));text('gm-five-winrate',`${model.winRate}%`);text('gm-mistake-cost',money(-model.mistakeCost));text('gm-equity-delta',money(model.equitySeries.at(-1)||0));renderSpark('gm-winrate-spark',model.cumulativeWinRate);renderSpark('gm-equity-spark',model.equitySeries);text('gm-review-status',latest?.status||'empty');text('gm-review-title',latest?`Сесія ${latest.trade_date}`:'Ще немає розбору');text('gm-debrief-text',latest?.debrief||'Завершіть торгову сесію — Grandmaster збере доказовий розбір.');const take=[...list(latest?.mistakes),...list(latest?.strengths)].slice(0,7);document.getElementById('gm-takeaways').innerHTML=(take.length?take:['Зафіксуйте setup, RVOL, ATR та invalidation.']).map((v)=>`<li>${escapeHtml(v)}</li>`).join('');document.getElementById('gm-next-rules').innerHTML=(list(latest?.next_session_rules).length?list(latest.next_session_rules):['Класифікувати setup до входу','Не входити без RVOL/volume confirmation','Поставити invalidation до натискання Short']).map((v)=>`<li>${escapeHtml(v)}</li>`).join('');const dna=model.dna;document.querySelector('#gm-dna-score strong').textContent=dna.discipline;const badges=(items,empty)=>items.length?items.map((v)=>`<span title="${v.count} згадувань">${escapeHtml(v.label)}</span>`).join(''):`<span>${empty}</span>`;document.getElementById('gm-risk-badges').innerHTML=badges(dna.risks,'Ризиків недостатньо для висновку');const strengths=document.getElementById('gm-strength-badges');strengths.classList.add('is-strength');strengths.innerHTML=badges(dna.strengths,'Накопичуємо evidence');document.getElementById('gm-review-history').innerHTML=model.days.slice().reverse().map((d)=>`<div class="gm-history-row ${number(d.pnl)>=0?'is-win':'is-loss'}"><span>${escapeHtml(d.trade_date)}</span><small>${(d.daily_metrics?.trades||[]).length} trades</small><b>${money(d.pnl)}</b></div>`).join('');}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
export async function renderGrandmasterDashboard(){const loading=document.getElementById('gm-loading');const content=document.getElementById('gm-content');const errorBox=document.getElementById('gm-error');if(!loading||!content)return;loading.hidden=false;content.hidden=true;errorBox.hidden=true;try{const userId=state.myUserId||(await supabase.auth.getUser()).data.user?.id;if(!userId)throw new Error('Потрібна авторизація');const [reviews,days,feedback]=await Promise.all([supabase.from('daily_reviews').select('trade_date,status,debrief,strengths,mistakes,next_session_rules,evidence,model_name').eq('user_id',userId).order('trade_date',{ascending:false}).limit(30),supabase.from('journal_days').select('trade_date,pnl,daily_metrics').eq('user_id',userId).order('trade_date',{ascending:false}).limit(40),supabase.from('ai_feedback').select('rating,correction,context,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(100)]);if(reviews.error)throw reviews.error;if(days.error)throw days.error;render(buildGrandmasterView(reviews.data||[],days.data||[],feedback.error?[]:feedback.data||[]));content.hidden=false;}catch(error){text('gm-error-text',error.message||'Не вдалося завантажити дані');errorBox.hidden=false;}finally{loading.hidden=true}}
export async function renderTraderDNAGlance(){if(!document.getElementById('dna-glance'))return;try{const userId=state.myUserId||(await supabase.auth.getUser()).data.user?.id;if(!userId)return;const [reviews,days,feedback]=await Promise.all([supabase.from('daily_reviews').select('trade_date,strengths,mistakes').eq('user_id',userId).order('trade_date',{ascending:false}).limit(7),supabase.from('journal_days').select('trade_date,pnl,daily_metrics').eq('user_id',userId).order('trade_date',{ascending:false}).limit(30),supabase.from('ai_feedback').select('rating').eq('user_id',userId).order('created_at',{ascending:false}).limit(50)]);const dna=buildTraderDNA(reviews.data||[],days.data||[],feedback.data||[]);text('dna-glance-score',dna.discipline);text('dna-glance-risk',dna.risks[0]?.label||'Немає повторюваного ризику');text('dna-glance-risk-meta',dna.risks[0]?`${dna.risks[0].count} повтори за 7 reviews`:'Накопичуємо evidence');text('dna-glance-strength',dna.strengths[0]?.label||'Потрібно більше угод');}catch{ text('dna-glance-risk','DNA тимчасово недоступна');}}
export function initGrandmasterDashboard(){document.getElementById('gm-refresh')?.addEventListener('click',()=>renderGrandmasterDashboard());}
