-- Production RLS policies.
-- Run after database/01_init_tables.sql and database/ai/01_ai_request_logs.sql.
--
-- Note: run database/security/02_login_helpers.sql first if you want the auth
-- screen to resolve nick -> email and load public team names without direct
-- anon access to profiles.

CREATE TABLE IF NOT EXISTS public.journal_months (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_doc_name TEXT NOT NULL,
    nick TEXT,
    month_key TEXT NOT NULL,
    data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_doc_name, month_key)
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS team TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'trader';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mentor_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS private_notes JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.screenshots ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.screenshots s
SET user_id = j.user_id
FROM public.journal_days j
WHERE s.journal_id = j.id
  AND s.user_id IS NULL;

CREATE OR REPLACE FUNCTION public.app_is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE id = auth.uid()
          AND role = 'admin'
    );
$$;

CREATE OR REPLACE FUNCTION public.app_is_mentor()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE id = auth.uid()
          AND (role IN ('admin', 'mentor') OR mentor_enabled = TRUE)
    );
$$;

CREATE OR REPLACE FUNCTION public.app_user_team(target_user_id UUID)
RETURNS TEXT
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(team, '')
    FROM public.profiles
    WHERE id = target_user_id
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.app_same_team(target_user_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(public.app_user_team(auth.uid()), '') = COALESCE(public.app_user_team(target_user_id), '');
$$;

CREATE OR REPLACE FUNCTION public.app_user_id_for_nick(target_nick TEXT)
RETURNS UUID
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT id
    FROM public.profiles
    WHERE nick = target_nick
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.app_storage_owner_user_id(owner_key TEXT)
RETURNS UUID
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT CASE
        WHEN owner_key ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            THEN owner_key::UUID
        ELSE public.app_user_id_for_nick(owner_key)
    END;
$$;

CREATE OR REPLACE FUNCTION public.app_can_view_user(target_user_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT auth.uid() = target_user_id
        OR public.app_is_admin()
        OR (public.app_is_mentor() AND public.app_same_team(target_user_id));
$$;

CREATE OR REPLACE FUNCTION public.app_can_view_nick(target_nick TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT public.app_can_view_user(public.app_user_id_for_nick(target_nick));
$$;

CREATE OR REPLACE FUNCTION public.app_can_view_storage_owner(owner_key TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT public.app_can_view_user(public.app_storage_owner_user_id(owner_key));
$$;

CREATE OR REPLACE FUNCTION public.app_protect_profile_privileged_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF auth.role() = 'service_role' OR current_setting('app.telegram_profile_repair', TRUE) = 'on' THEN
        RETURN NEW;
    END IF;

    IF public.app_is_admin() THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'INSERT' THEN
        NEW.role := 'trader';
        NEW.mentor_enabled := FALSE;
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        NEW.role := OLD.role;
        NEW.mentor_enabled := OLD.mentor_enabled;
        NEW.team := OLD.team;
        NEW.nick := OLD.nick;
        NEW.email := OLD.email;
        RETURN NEW;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_protect_privileged_fields ON public.profiles;
CREATE TRIGGER trg_profiles_protect_privileged_fields
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.app_protect_profile_privileged_fields();

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_months ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screenshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_request_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_read_for_login_and_team ON public.profiles;
DROP POLICY IF EXISTS profiles_read_authenticated ON public.profiles;
CREATE POLICY profiles_read_authenticated
ON public.profiles
FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS profiles_insert_own ON public.profiles;
CREATE POLICY profiles_insert_own
ON public.profiles
FOR INSERT
TO authenticated
WITH CHECK (id = auth.uid() OR public.app_is_admin());

DROP POLICY IF EXISTS profiles_update_own_or_admin ON public.profiles;
CREATE POLICY profiles_update_own_or_admin
ON public.profiles
FOR UPDATE
TO authenticated
USING (id = auth.uid() OR public.app_is_admin())
WITH CHECK (id = auth.uid() OR public.app_is_admin());

DROP POLICY IF EXISTS profiles_delete_admin ON public.profiles;
CREATE POLICY profiles_delete_admin
ON public.profiles
FOR DELETE
TO authenticated
USING (public.app_is_admin());

DROP POLICY IF EXISTS journal_days_read_owner_or_same_team_mentor ON public.journal_days;
CREATE POLICY journal_days_read_owner_or_same_team_mentor
ON public.journal_days
FOR SELECT
TO authenticated
USING (public.app_can_view_user(user_id));

DROP POLICY IF EXISTS journal_days_insert_owner_or_same_team_mentor ON public.journal_days;
CREATE POLICY journal_days_insert_owner_or_same_team_mentor
ON public.journal_days
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id OR public.app_is_admin() OR (public.app_is_mentor() AND public.app_same_team(user_id)));

DROP POLICY IF EXISTS journal_days_update_owner_or_same_team_mentor ON public.journal_days;
CREATE POLICY journal_days_update_owner_or_same_team_mentor
ON public.journal_days
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin() OR (public.app_is_mentor() AND public.app_same_team(user_id)))
WITH CHECK (auth.uid() = user_id OR public.app_is_admin() OR (public.app_is_mentor() AND public.app_same_team(user_id)));

DROP POLICY IF EXISTS journal_days_delete_owner_or_admin ON public.journal_days;
CREATE POLICY journal_days_delete_owner_or_admin
ON public.journal_days
FOR DELETE
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin());

DROP POLICY IF EXISTS journal_months_admin_only ON public.journal_months;
CREATE POLICY journal_months_admin_only
ON public.journal_months
FOR ALL
TO authenticated
USING (public.app_is_admin())
WITH CHECK (public.app_is_admin());

DROP POLICY IF EXISTS screenshots_owner_or_admin ON public.screenshots;
CREATE POLICY screenshots_owner_or_admin
ON public.screenshots
FOR ALL
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin())
WITH CHECK (auth.uid() = user_id OR public.app_is_admin());

DROP POLICY IF EXISTS teams_read_authenticated ON public.teams;
CREATE POLICY teams_read_authenticated
ON public.teams
FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS teams_admin_write ON public.teams;
CREATE POLICY teams_admin_write
ON public.teams
FOR ALL
TO authenticated
USING (public.app_is_admin())
WITH CHECK (public.app_is_admin());

DROP POLICY IF EXISTS ai_logs_owner_only ON public.ai_request_logs;
CREATE POLICY ai_logs_owner_only
ON public.ai_request_logs
FOR ALL
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin())
WITH CHECK (auth.uid() = user_id OR public.app_is_admin());

DROP POLICY IF EXISTS storage_screenshots_read_owner_or_same_team_mentor ON storage.objects;
CREATE POLICY storage_screenshots_read_owner_or_same_team_mentor
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'screenshots'
    AND public.app_can_view_storage_owner(split_part(name, '/', 1))
);

DROP POLICY IF EXISTS storage_screenshots_write_owner_or_admin ON storage.objects;
CREATE POLICY storage_screenshots_write_owner_or_admin
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
);

DROP POLICY IF EXISTS storage_screenshots_update_owner_or_admin ON storage.objects;
CREATE POLICY storage_screenshots_update_owner_or_admin
ON storage.objects
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
)
WITH CHECK (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
);

DROP POLICY IF EXISTS storage_screenshots_delete_owner_or_admin ON storage.objects;
CREATE POLICY storage_screenshots_delete_owner_or_admin
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
);

DROP POLICY IF EXISTS storage_backgrounds_owner_or_admin ON storage.objects;
CREATE POLICY storage_backgrounds_owner_or_admin
ON storage.objects
FOR ALL
TO authenticated
USING (
    bucket_id = 'backgrounds'
    AND (public.app_is_admin() OR split_part(name, '/', 1) = auth.uid()::TEXT)
)
WITH CHECK (
    bucket_id = 'backgrounds'
    AND (public.app_is_admin() OR split_part(name, '/', 1) = auth.uid()::TEXT)
);

NOTIFY pgrst, 'reload schema';
