-- Production RLS policies.
-- Run after database/01_init_tables.sql and database/ai/01_ai_request_logs.sql.
--
-- Note: run database/security/02_login_helpers.sql first if you want the auth
-- screen to resolve nick -> email and load public team names without direct
-- anon access to profiles.

CREATE TABLE IF NOT EXISTS public.journal_months (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_doc_name TEXT NOT NULL,
    nick TEXT,
    month_key TEXT NOT NULL,
    data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_doc_name, month_key)
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS team TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'trader';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mentor_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS private_notes JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.screenshots ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.screenshots s
SET user_id = j.user_id
FROM public.journal_days j
WHERE s.journal_id = j.id
  AND s.user_id IS NULL;

CREATE OR REPLACE FUNCTION public.app_is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE id = auth.uid()
          AND role = 'admin'
    );
$$;

CREATE OR REPLACE FUNCTION public.app_is_mentor()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles
        WHERE id = auth.uid()
          AND (role = 'mentor' OR mentor_enabled = TRUE)
    );
$$;

CREATE OR REPLACE FUNCTION public.app_user_team(target_user_id UUID)
RETURNS TEXT
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(team, '')
    FROM public.profiles
    WHERE id = target_user_id
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.app_same_team(target_user_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(public.app_user_team(auth.uid()), '') = COALESCE(public.app_user_team(target_user_id), '');
$$;

CREATE OR REPLACE FUNCTION public.app_user_id_for_nick(target_nick TEXT)
RETURNS UUID
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT id
    FROM public.profiles
    WHERE nick = target_nick
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.app_storage_owner_user_id(owner_key TEXT)
RETURNS UUID
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT CASE
        WHEN owner_key ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            THEN owner_key::UUID
        ELSE public.app_user_id_for_nick(owner_key)
    END;
$$;

CREATE OR REPLACE FUNCTION public.app_can_view_user(target_user_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT auth.uid() IS NOT NULL AND target_user_id IS NOT NULL;
$$;

CREATE OR REPLACE FUNCTION public.app_can_view_nick(target_nick TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT public.app_can_view_user(public.app_user_id_for_nick(target_nick));
$$;

CREATE OR REPLACE FUNCTION public.app_can_view_storage_owner(owner_key TEXT)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT public.app_can_view_user(public.app_storage_owner_user_id(owner_key));
$$;

CREATE OR REPLACE FUNCTION public.app_protect_profile_privileged_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF auth.role() = 'service_role' OR current_setting('app.telegram_profile_repair', TRUE) = 'on' THEN
        RETURN NEW;
    END IF;

    IF public.app_is_admin() THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'INSERT' THEN
        NEW.role := 'trader';
        NEW.mentor_enabled := FALSE;
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        NEW.role := OLD.role;
        NEW.mentor_enabled := OLD.mentor_enabled;
        NEW.team := OLD.team;
        NEW.nick := OLD.nick;
        NEW.email := OLD.email;
        RETURN NEW;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_protect_privileged_fields ON public.profiles;
CREATE TRIGGER trg_profiles_protect_privileged_fields
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.app_protect_profile_privileged_fields();

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_months ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screenshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_request_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_read_for_login_and_team ON public.profiles;
DROP POLICY IF EXISTS profiles_read_authenticated ON public.profiles;
CREATE POLICY profiles_read_authenticated
ON public.profiles
FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS profiles_insert_own ON public.profiles;
CREATE POLICY profiles_insert_own
ON public.profiles
FOR INSERT
TO authenticated
WITH CHECK (id = auth.uid() OR public.app_is_admin());

DROP POLICY IF EXISTS profiles_update_own_or_admin ON public.profiles;
CREATE POLICY profiles_update_own_or_admin
ON public.profiles
FOR UPDATE
TO authenticated
USING (id = auth.uid() OR public.app_is_admin())
WITH CHECK (id = auth.uid() OR public.app_is_admin());

DROP POLICY IF EXISTS profiles_delete_admin ON public.profiles;
CREATE POLICY profiles_delete_admin
ON public.profiles
FOR DELETE
TO authenticated
USING (public.app_is_admin());

DROP POLICY IF EXISTS journal_days_read_owner_or_same_team_mentor ON public.journal_days;
CREATE POLICY journal_days_read_owner_or_same_team_mentor
ON public.journal_days
FOR SELECT
TO authenticated
USING (public.app_can_view_user(user_id));

DROP POLICY IF EXISTS journal_days_insert_owner_or_same_team_mentor ON public.journal_days;
CREATE POLICY journal_days_insert_owner_or_same_team_mentor
ON public.journal_days
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS journal_days_update_owner_or_same_team_mentor ON public.journal_days;
CREATE POLICY journal_days_update_owner_or_same_team_mentor
ON public.journal_days
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS journal_days_delete_owner_or_admin ON public.journal_days;
CREATE POLICY journal_days_delete_owner_or_admin
ON public.journal_days
FOR DELETE
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin());

DROP POLICY IF EXISTS journal_months_admin_only ON public.journal_months;
CREATE POLICY journal_months_admin_only
ON public.journal_months
FOR ALL
TO authenticated
USING (public.app_is_admin())
WITH CHECK (public.app_is_admin());

DROP POLICY IF EXISTS screenshots_owner_or_admin ON public.screenshots;
CREATE POLICY screenshots_owner_or_admin
ON public.screenshots
FOR ALL
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin())
WITH CHECK (auth.uid() = user_id OR public.app_is_admin());

DROP POLICY IF EXISTS teams_read_authenticated ON public.teams;
CREATE POLICY teams_read_authenticated
ON public.teams
FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS teams_admin_write ON public.teams;
CREATE POLICY teams_admin_write
ON public.teams
FOR ALL
TO authenticated
USING (public.app_is_admin())
WITH CHECK (public.app_is_admin());

DROP POLICY IF EXISTS ai_logs_owner_only ON public.ai_request_logs;
CREATE POLICY ai_logs_owner_only
ON public.ai_request_logs
FOR ALL
TO authenticated
USING (auth.uid() = user_id OR public.app_is_admin())
WITH CHECK (auth.uid() = user_id OR public.app_is_admin());

DROP POLICY IF EXISTS storage_screenshots_read_owner_or_same_team_mentor ON storage.objects;
CREATE POLICY storage_screenshots_read_owner_or_same_team_mentor
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'screenshots'
    AND auth.uid() IS NOT NULL
);

DROP POLICY IF EXISTS storage_screenshots_write_owner_or_admin ON storage.objects;
CREATE POLICY storage_screenshots_write_owner_or_admin
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
);

DROP POLICY IF EXISTS storage_screenshots_update_owner_or_admin ON storage.objects;
CREATE POLICY storage_screenshots_update_owner_or_admin
ON storage.objects
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
)
WITH CHECK (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
);

DROP POLICY IF EXISTS storage_screenshots_delete_owner_or_admin ON storage.objects;
CREATE POLICY storage_screenshots_delete_owner_or_admin
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'screenshots'
    AND (
        public.app_is_admin()
        OR public.app_storage_owner_user_id(split_part(name, '/', 1)) = auth.uid()
    )
);

DROP POLICY IF EXISTS storage_backgrounds_owner_or_admin ON storage.objects;
CREATE POLICY storage_backgrounds_owner_or_admin
ON storage.objects
FOR ALL
TO authenticated
USING (
    bucket_id = 'backgrounds'
    AND (public.app_is_admin() OR split_part(name, '/', 1) = auth.uid()::TEXT)
)
WITH CHECK (
    bucket_id = 'backgrounds'
    AND (public.app_is_admin() OR split_part(name, '/', 1) = auth.uid()::TEXT)
);

CREATE OR REPLACE FUNCTION public.save_mentor_comment(
    target_user_id UUID,
    target_trade_date DATE,
    comment_text TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    caller public.profiles%ROWTYPE;
BEGIN
    SELECT *
    INTO caller
    FROM public.profiles
    WHERE id = auth.uid();

    IF caller.id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    IF NOT (caller.role = 'mentor' OR caller.mentor_enabled = TRUE) THEN
        RAISE EXCEPTION 'Only mentors can write mentor comments';
    END IF;

    IF target_user_id = caller.id THEN
        RAISE EXCEPTION 'Mentor comment is only for another profile';
    END IF;

    INSERT INTO public.journal_days (user_id, trade_date, mentor_comment, daily_metrics)
    VALUES (target_user_id, target_trade_date, COALESCE(comment_text, ''), '{}'::jsonb)
    ON CONFLICT (user_id, trade_date)
    DO UPDATE SET mentor_comment = EXCLUDED.mentor_comment;
END;
$$;

GRANT EXECUTE ON FUNCTION public.save_mentor_comment(UUID, DATE, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.accept_mentor_review_request(
    target_user_id UUID,
    target_trade_date DATE,
    request_kind TEXT,
    screen_path TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    caller public.profiles%ROWTYPE;
    metrics JSONB;
    slot JSONB;
    path TEXT[];
BEGIN
    SELECT *
    INTO caller
    FROM public.profiles
    WHERE id = auth.uid();

    IF caller.id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    IF NOT (caller.role = 'mentor' OR caller.mentor_enabled = TRUE) THEN
        RAISE EXCEPTION 'Only mentors can accept review requests';
    END IF;

    IF target_user_id = caller.id THEN
        RAISE EXCEPTION 'Review request acceptance is only for another profile';
    END IF;

    SELECT COALESCE(daily_metrics, '{}'::jsonb)
    INTO metrics
    FROM public.journal_days
    WHERE user_id = target_user_id
      AND trade_date = target_trade_date
    FOR UPDATE;

    IF metrics IS NULL THEN
        RETURN FALSE;
    END IF;

    IF request_kind = 'screen_item' THEN
        IF COALESCE(screen_path, '') = '' THEN
            RETURN FALSE;
        END IF;
        path := ARRAY['review_requests', 'by_screen', screen_path];
    ELSE
        path := ARRAY['review_requests', request_kind];
    END IF;

    slot := metrics #> path;
    IF slot IS NULL
        OR slot->>'status' <> 'pending'
        OR slot->>'mentor_user_id' <> caller.id::TEXT THEN
        RETURN FALSE;
    END IF;

    slot := jsonb_set(slot, ARRAY['status'], to_jsonb('accepted'::TEXT), TRUE);
    slot := jsonb_set(slot, ARRAY['accepted_at'], to_jsonb(NOW()::TEXT), TRUE);
    slot := jsonb_set(slot, ARRAY['accepted_by'], to_jsonb(COALESCE(caller.nick, '')::TEXT), TRUE);
    metrics := jsonb_set(metrics, path, slot, TRUE);

    UPDATE public.journal_days
    SET daily_metrics = metrics
    WHERE user_id = target_user_id
      AND trade_date = target_trade_date;

    RETURN TRUE;
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_mentor_review_request(UUID, DATE, TEXT, TEXT) TO authenticated;

NOTIFY pgrst, 'reload schema';
