-- Do not open SELECT on public.profiles. The settings column stores API keys.
-- The team roster is public.team_directory(), and journals use app_can_read_journal().
-- See supabase/migrations/20260929130000_team_directory.sql.
