-- Server-side compressed journal backups.
-- Run this in Supabase SQL Editor before relying on server backups.

CREATE TABLE IF NOT EXISTS public.journal_backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_id TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reason TEXT DEFAULT 'backup',
    nick TEXT,
    backup_created_at TIMESTAMPTZ DEFAULT NOW(),
    backup_data JSONB NOT NULL,
    raw_bytes INTEGER DEFAULT 0,
    stored_bytes INTEGER DEFAULT 0,
    days INTEGER DEFAULT 0,
    encoding TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, backup_id)
);

CREATE INDEX IF NOT EXISTS idx_journal_backups_user_created
ON public.journal_backups (user_id, backup_created_at DESC, created_at DESC);

ALTER TABLE public.journal_backups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS journal_backups_read_own ON public.journal_backups;
CREATE POLICY journal_backups_read_own
ON public.journal_backups
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS journal_backups_read_admin ON public.journal_backups;
CREATE POLICY journal_backups_read_admin
ON public.journal_backups
FOR SELECT
TO authenticated
USING (public.app_is_admin());

DROP POLICY IF EXISTS journal_backups_insert_own ON public.journal_backups;
CREATE POLICY journal_backups_insert_own
ON public.journal_backups
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS journal_backups_update_own ON public.journal_backups;
CREATE POLICY journal_backups_update_own
ON public.journal_backups
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS journal_backups_delete_own ON public.journal_backups;
CREATE POLICY journal_backups_delete_own
ON public.journal_backups
FOR DELETE
TO authenticated
USING (user_id = auth.uid());

NOTIFY pgrst, 'reload schema';
