import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { buildGrandmasterView, buildTraderDNA, sparklinePoints } from '../js/grandmaster_core.js';
import { filterTerminalRows } from '../js/terminal_trade_filters.js';
import { shortcutAction } from '../js/terminal_shortcuts.js';

test('Grandmaster view builds five-session KPI, factual mistake cost and DNA', () => { const days=[{trade_date:'2026-08-07',pnl:-100,daily_metrics:{trades:[{symbol:'A',setup:'ORB',net:-100,rvol:500}]}},{trade_date:'2026-08-06',pnl:200,daily_metrics:{trades:[{symbol:'B',setup:'pump-and-dump',net:200,rvol:1200},{symbol:'C',setup:'pump-and-dump',net:50,rvol:1500}]}},{trade_date:'2026-08-05',pnl:50,daily_metrics:{trades:[]}}];const reviews=[{trade_date:'2026-08-07',mistakes:['Chasing Entries'],strengths:[],next_session_rules:['Wait for retest'],debrief:'Evidence-backed debrief'}];const model=buildGrandmasterView(reviews,days,[]);assert.equal(model.pnl,150);assert.equal(model.mistakeCost,100);assert.equal(model.latest.trade_date,'2026-08-07');assert.ok(model.dna.risks.some((v)=>v.label==='Chasing Entries'));assert.ok(model.dna.strengths.some((v)=>/pump-and-dump: 100% WR/.test(v.label)));});
test('Trader DNA penalizes recurring review mistakes and negative feedback',()=>{const dna=buildTraderDNA([{mistakes:['Premature ORB'],strengths:[]},{mistakes:['Premature ORB'],strengths:[]}],[],[{rating:-1}]);assert.equal(dna.risks[0].count,2);assert.ok(dna.discipline<100);});
test('SVG sparkline stays inside its viewbox',()=>{const points=sparklinePoints([-10,20,5,40]);assert.equal(points.split(' ').length,4);for(const point of points.split(' ')){const[x,y]=point.split(',').map(Number);assert.ok(x>=0&&x<=160&&y>=0&&y<=42);}});
test('terminal filters combine ticker, RVOL, ATR and premarket time instantly',()=>{const rows=[{trade:{symbol:'XYZ',rvol:1200,atr:1.2,opened:'2026-08-07 04:35'}},{trade:{symbol:'ABC',rvol:300,atr:.3,opened:'2026-08-07 08:00'}}];const result=filterTerminalRows(rows,{query:'xy',minRvol:1000,minAtr:1,timeFrom:'04:00',timeTo:'05:00'});assert.equal(result.length,1);assert.equal(result[0].trade.symbol,'XYZ');});
test('terminal shortcuts ignore arrows in inputs and map fast actions',()=>{assert.equal(shortcutAction({key:'n',altKey:true,target:{matches:()=>false}}),'new-trade');assert.equal(shortcutAction({key:'Enter',ctrlKey:true,target:{matches:()=>true}}),'save-trade');assert.equal(shortcutAction({key:'ArrowRight',target:{matches:()=>true}}),'');assert.equal(shortcutAction({key:'ArrowLeft',target:{matches:()=>false}}),'previous-chart');});
test('Phase 4 page, dashboard DNA and route are wired into the application shell',async()=>{const[index,sidebar,view,ui]=await Promise.all([readFile(new URL('../index.html',import.meta.url),'utf8'),readFile(new URL('../partials/layout/app-sidebar.html',import.meta.url),'utf8'),readFile(new URL('../partials/views/debrief-view.html',import.meta.url),'utf8'),readFile(new URL('../js/ui.js',import.meta.url),'utf8')]);assert.match(index,/debrief-view\.html/);assert.match(index,/22_grandmaster\.css/);assert.match(sidebar,/data-tab="debrief"/);assert.match(view,/gm-winrate-spark/);assert.match(view,/gm-dna-score/);assert.match(ui,/debrief:\s*'\/debrief'/);});
