-- Admin-reviewed multimodal memory for the AI learning centre.
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.ai_learning_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trigger_type TEXT NOT NULL CHECK (trigger_type IN ('manual', 'cron')),
    status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'partial', 'failed')),
    model_name TEXT NOT NULL DEFAULT 'gemini-2.5-flash',
    prompt_version TEXT NOT NULL DEFAULT 'entry-mistake-v1',
    scanned_count INTEGER NOT NULL DEFAULT 0,
    created_count INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    estimated_cost_usd NUMERIC NOT NULL DEFAULT 0,
    error_summary JSONB NOT NULL DEFAULT '[]'::jsonb,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.ai_learning_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_version TEXT NOT NULL,
    memory_version INTEGER NOT NULL DEFAULT 0,
    model_name TEXT NOT NULL DEFAULT 'gemini-2.5-flash',
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ai_learning_one_active_version
    ON public.ai_learning_versions(active) WHERE active;

INSERT INTO public.ai_learning_versions (prompt_version, memory_version, model_name, active)
SELECT 'entry-mistake-v1', 0, 'gemini-2.5-flash', TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.ai_learning_versions WHERE active);

CREATE OR REPLACE FUNCTION public.increment_ai_learning_memory_version()
RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE next_version INTEGER;
BEGIN
    IF NOT public.app_is_admin() THEN RAISE EXCEPTION 'Admin only'; END IF;
    UPDATE public.ai_learning_versions
    SET memory_version = memory_version + 1
    WHERE active
    RETURNING memory_version INTO next_version;
    RETURN COALESCE(next_version, 0);
END;
$$;

CREATE TABLE IF NOT EXISTS public.ai_learning_examples (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    journal_day_id BIGINT REFERENCES public.journal_days(id) ON DELETE CASCADE,
    trade_date DATE NOT NULL,
    trade_key TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    source_version INTEGER NOT NULL DEFAULT 1,
    source_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    outcome JSONB NOT NULL DEFAULT '{}'::jsonb,
    screenshot_path TEXT,
    screenshot_mime_type TEXT,
    ai_pattern_key TEXT,
    ai_label TEXT,
    ai_confidence NUMERIC,
    ai_explanation TEXT,
    visual_evidence TEXT,
    journal_evidence TEXT,
    alternative_pattern_key TEXT,
    review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'approved', 'corrected', 'rejected')),
    reviewed_pattern_key TEXT,
    review_note TEXT,
    reviewed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    embedding extensions.vector(768),
    model_name TEXT NOT NULL DEFAULT 'gemini-2.5-flash',
    prompt_version TEXT NOT NULL DEFAULT 'entry-mistake-v1',
    run_id UUID REFERENCES public.ai_learning_runs(id) ON DELETE SET NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (content_hash)
);

CREATE INDEX IF NOT EXISTS ai_learning_examples_review_idx
    ON public.ai_learning_examples(review_status, is_current, created_at DESC);
CREATE INDEX IF NOT EXISTS ai_learning_examples_user_trade_idx
    ON public.ai_learning_examples(user_id, trade_key, is_current);
CREATE INDEX IF NOT EXISTS ai_learning_examples_embedding_idx
    ON public.ai_learning_examples USING hnsw (embedding extensions.vector_cosine_ops)
    WHERE embedding IS NOT NULL AND review_status IN ('approved', 'corrected') AND is_current;

CREATE OR REPLACE FUNCTION public.match_ai_learning_examples(
    query_embedding extensions.vector(768),
    match_count INTEGER DEFAULT 5
)
RETURNS TABLE (id UUID, pattern_key TEXT, similarity DOUBLE PRECISION, source_snapshot JSONB, outcome JSONB)
LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = public, extensions
AS $$
    SELECT e.id,
           COALESCE(e.reviewed_pattern_key, e.ai_pattern_key),
           1 - (e.embedding <=> query_embedding),
           e.source_snapshot,
           e.outcome
    FROM public.ai_learning_examples e
    WHERE e.embedding IS NOT NULL
      AND e.is_current
      AND e.review_status IN ('approved', 'corrected')
    ORDER BY e.embedding <=> query_embedding
    LIMIT LEAST(GREATEST(match_count, 1), 10);
$$;

ALTER TABLE public.ai_learning_examples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_learning_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_learning_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ai_learning_examples_admin_all ON public.ai_learning_examples;
CREATE POLICY ai_learning_examples_admin_all ON public.ai_learning_examples
FOR ALL TO authenticated USING (public.app_is_admin()) WITH CHECK (public.app_is_admin());
DROP POLICY IF EXISTS ai_learning_runs_admin_all ON public.ai_learning_runs;
CREATE POLICY ai_learning_runs_admin_all ON public.ai_learning_runs
FOR ALL TO authenticated USING (public.app_is_admin()) WITH CHECK (public.app_is_admin());
DROP POLICY IF EXISTS ai_learning_versions_admin_all ON public.ai_learning_versions;
CREATE POLICY ai_learning_versions_admin_all ON public.ai_learning_versions
FOR ALL TO authenticated USING (public.app_is_admin()) WITH CHECK (public.app_is_admin());

REVOKE ALL ON FUNCTION public.match_ai_learning_examples(extensions.vector, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.match_ai_learning_examples(extensions.vector, INTEGER) TO service_role;

NOTIFY pgrst, 'reload schema';
