-- Supabase schema for the Firebase -> Supabase journal migration.
-- Run this in the Supabase SQL editor, then reload PostgREST schema.

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nick TEXT UNIQUE NOT NULL,
    email TEXT,
    first_name TEXT,
    last_name TEXT,
    team TEXT,
    role TEXT DEFAULT 'trader',
    mentor_enabled BOOLEAN DEFAULT FALSE,
    private_notes JSONB DEFAULT '{}'::jsonb,
    settings JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS team TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'trader';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mentor_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS private_notes JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS public.journal_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    trade_date DATE NOT NULL,
    pnl NUMERIC,
    gross_pnl NUMERIC,
    commissions NUMERIC,
    locates NUMERIC,
    kf NUMERIC,
    notes TEXT DEFAULT '',
    mentor_comment TEXT DEFAULT '',
    ai_advice TEXT DEFAULT '',
    daily_metrics JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, trade_date)
);

CREATE INDEX IF NOT EXISTS idx_journal_days_user_date
    ON public.journal_days(user_id, trade_date);

-- Kept only for backwards compatibility with older code/data. New code writes
-- mentor comments and journal entries to journal_days.
CREATE TABLE IF NOT EXISTS public.journal_months (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_doc_name TEXT NOT NULL,
    nick TEXT,
    month_key TEXT NOT NULL,
    data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_doc_name, month_key)
);

CREATE TABLE IF NOT EXISTS public.screenshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO storage.buckets (id, name, public)
VALUES
    ('screenshots', 'screenshots', false),
    ('backgrounds', 'backgrounds', false),
    ('assets', 'assets', false),
    ('files', 'files', false)
ON CONFLICT (id) DO NOTHING;

-- Secure by default: keep RLS enabled. Apply database/security/01_enable_rls.sql
-- after this file to install the owner/mentor/admin policies.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_months ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screenshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
