-- Server-side Google Sheets sync settings.
-- Run this in Supabase SQL Editor after database/01_init_tables.sql.

CREATE TABLE IF NOT EXISTS public.google_sheet_sync_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    spreadsheet_id TEXT NOT NULL,
    sheet_title TEXT DEFAULT '',
    selected_file_name TEXT DEFAULT '',
    data_start_row INTEGER,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    last_sync_at TIMESTAMPTZ,
    last_sync_status TEXT,
    last_sync_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, spreadsheet_id, sheet_title)
);

CREATE INDEX IF NOT EXISTS idx_google_sheet_sync_configs_enabled
    ON public.google_sheet_sync_configs(enabled)
    WHERE enabled = TRUE;

ALTER TABLE public.google_sheet_sync_configs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP POLICY IF EXISTS google_sheet_sync_configs_read_owner ON public.google_sheet_sync_configs;
CREATE POLICY google_sheet_sync_configs_read_owner
ON public.google_sheet_sync_configs
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS google_sheet_sync_configs_insert_owner ON public.google_sheet_sync_configs;
CREATE POLICY google_sheet_sync_configs_insert_owner
ON public.google_sheet_sync_configs
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS google_sheet_sync_configs_update_owner ON public.google_sheet_sync_configs;
CREATE POLICY google_sheet_sync_configs_update_owner
ON public.google_sheet_sync_configs
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS trg_google_sheet_sync_configs_updated_at ON public.google_sheet_sync_configs;
CREATE TRIGGER trg_google_sheet_sync_configs_updated_at
BEFORE UPDATE ON public.google_sheet_sync_configs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

NOTIFY pgrst, 'reload schema';
