-- Service bot API keys for read-only external integrations.
-- Run after database/01_init_tables.sql and database/security/01_enable_rls.sql.

CREATE TABLE IF NOT EXISTS public.bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Service bot',
    bot_type TEXT NOT NULL DEFAULT 'service',
    api_key TEXT UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    extra_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bots_api_key
    ON public.bots(api_key)
    WHERE api_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bots_user_id
    ON public.bots(user_id);

ALTER TABLE public.bots ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_bots_updated_at ON public.bots;
CREATE TRIGGER trg_bots_updated_at
BEFORE UPDATE ON public.bots
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP POLICY IF EXISTS bots_admin_read ON public.bots;
CREATE POLICY bots_admin_read
ON public.bots
FOR SELECT
TO authenticated
USING (public.app_is_admin());

DROP POLICY IF EXISTS bots_admin_insert ON public.bots;
CREATE POLICY bots_admin_insert
ON public.bots
FOR INSERT
TO authenticated
WITH CHECK (public.app_is_admin());

DROP POLICY IF EXISTS bots_admin_update ON public.bots;
CREATE POLICY bots_admin_update
ON public.bots
FOR UPDATE
TO authenticated
USING (public.app_is_admin())
WITH CHECK (public.app_is_admin());

DROP POLICY IF EXISTS bots_admin_delete ON public.bots;
CREATE POLICY bots_admin_delete
ON public.bots
FOR DELETE
TO authenticated
USING (public.app_is_admin());

NOTIFY pgrst, 'reload schema';
