import ExcelJS from 'exceljs';

const safeText = (value) => { const text = String(value ?? '').replace(/[\u0000-\u001f\u007f]+/g, ' ').trim(); return /^[=+\-@]/.test(text) ? `'${text}` : text; };
const finite = (value) => Number.isFinite(Number(value)) ? Number(value) : null;
const tradesOf = (day) => Array.isArray(day?.daily_metrics?.trades) ? day.daily_metrics.trades : [];
const navy = '152236'; const teal = '00BFA6'; const surface = 'E8EEF6'; const white = 'FFFFFF'; const red = 'F25F5C';

function styleHeader(row) { row.height = 24; row.eachCell((cell) => { cell.font = { bold: true, color: { argb: white } }; cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: navy } }; cell.alignment = { vertical: 'middle' }; }); }
function title(sheet, text, endColumn) { sheet.mergeCells(1, 1, 1, endColumn); const cell = sheet.getCell(1, 1); cell.value = text; cell.font = { size: 18, bold: true, color: { argb: white } }; cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: navy } }; cell.alignment = { vertical: 'middle' }; sheet.getRow(1).height = 34; sheet.views = [{ state: 'frozen', ySplit: 3, showGridLines: false }]; }
function tradeRows(days) { return (days || []).flatMap((day) => tradesOf(day).map((trade, index) => ({ date: day.trade_date, index: index + 1, time: trade.opened || trade.time || '', ticker: safeText(trade.symbol || trade.ticker), direction: safeText(trade.type || 'SHORT'), setup: safeText(trade.setup || trade.setupType), entry: finite(trade.entry), stop: finite(trade.stop), exit: finite(trade.exit), quantity: finite(trade.quantity || trade.qty || trade.shares), netPnl: finite(trade.net ?? trade.pnl), gapPct: finite(trade.gapPct), rvol: finite(trade.rvol), floatShares: finite(trade.floatShares), atr: finite(trade.atr), grade: safeText(trade.disciplineGrade), score: finite(trade.disciplineScore), reasons: safeText(Array.isArray(trade.disciplineReasons) ? trade.disciplineReasons.join('; ') : trade.disciplineReasons) })) ); }

export async function buildTradingWorkbook({ days = [], reviews = [], generatedAt = new Date() } = {}) {
    const workbook = new ExcelJS.Workbook(); workbook.creator = 'STRUM'; workbook.created = generatedAt; workbook.calcProperties.fullCalcOnLoad = true;
    const rows = tradeRows(days);
    const raw = workbook.addWorksheet('Raw Trade Data'); title(raw, 'STRUM · Raw Trade Data', 18); raw.getCell('A2').value = `Generated ${generatedAt.toISOString()}`;
    raw.columns = [{ key:'date',width:13 },{ key:'index',width:8 },{ key:'time',width:10 },{ key:'ticker',width:12 },{ key:'direction',width:11 },{ key:'setup',width:25 },{ key:'entry',width:12 },{ key:'stop',width:12 },{ key:'exit',width:12 },{ key:'quantity',width:12 },{ key:'netPnl',width:14 },{ key:'gapPct',width:12 },{ key:'rvol',width:11 },{ key:'floatShares',width:16 },{ key:'atr',width:11 },{ key:'grade',width:12 },{ key:'score',width:15 },{ key:'reasons',width:38 }];
    const headers = ['Date','Trade #','Time ET','Ticker','Direction','Setup','Entry','Stop','Exit','Quantity','Net PnL','Gap %','RVOL','Float Shares','ATR','Discipline Grade','Discipline Score','Discipline Reasons']; raw.addRow(headers); styleHeader(raw.getRow(3)); rows.forEach((row) => raw.addRow(row)); raw.autoFilter = { from: 'A3', to: `R${Math.max(3, rows.length + 3)}` };
    raw.getColumn(11).numFmt = '$#,##0.00;[Red]-$#,##0.00'; raw.getColumn(12).numFmt = '0.00"%"'; raw.getColumn(14).numFmt = '#,##0'; raw.getColumn(18).alignment = { wrapText: true, vertical: 'top' };
    if (rows.length) { raw.addConditionalFormatting({ ref: `K4:K${rows.length + 3}`, rules: [{ type:'cellIs', operator:'lessThan', formulae:[0], style:{ font:{ color:{ argb:red } } } },{ type:'cellIs', operator:'greaterThanOrEqual', formulae:[0], style:{ font:{ color:{ argb:'16836B' } } } }] }); }

    const insights = workbook.addWorksheet('AI Insights & Debriefs'); title(insights, 'STRUM · AI Insights & Daily Debriefs', 7); insights.columns = [{width:13},{width:12},{width:18},{width:45},{width:45},{width:45},{width:24}]; insights.addRow(['Date','Status','Model','Debrief','Strengths','Next Session Rules','Mistakes']); styleHeader(insights.getRow(3));
    (reviews || []).forEach((review) => insights.addRow([review.trade_date, safeText(review.status), safeText(review.model_name), safeText(review.debrief), safeText((review.strengths || []).join('; ')), safeText((review.next_session_rules || []).join('; ')), safeText((review.mistakes || []).join('; '))])); insights.autoFilter = { from:'A3', to:`G${Math.max(3, (reviews || []).length + 3)}` }; ['D','E','F','G'].forEach((column) => { insights.getColumn(column).alignment = { wrapText:true, vertical:'top' }; });

    const summary = workbook.addWorksheet('Summary Dashboard'); title(summary, 'STRUM · Summary Dashboard', 8); summary.views = [{ showGridLines:false }];
    summary.getCell('A3').value='KPI'; summary.getCell('B3').value='Value'; styleHeader(summary.getRow(3));
    const last = Math.max(4, rows.length + 3); const kpis = [['Total Trades',{formula:`COUNTA('Raw Trade Data'!D4:D${last})`}],['Win Rate',{formula:`IFERROR(COUNTIF('Raw Trade Data'!K4:K${last},">0")/COUNT('Raw Trade Data'!K4:K${last}),0)`}],['Net PnL',{formula:`SUM('Raw Trade Data'!K4:K${last})`}],['Average Discipline',{formula:`IFERROR(AVERAGE('Raw Trade Data'!Q4:Q${last}),0)`}]]; kpis.forEach(([label,value]) => summary.addRow([label,value])); summary.getCell('B5').numFmt='0.0%'; summary.getCell('B6').numFmt='$#,##0.00;[Red]-$#,##0.00'; summary.getCell('B7').numFmt='0.0';
    summary.getCell('D3').value='Setup'; summary.getCell('E3').value='Trades'; summary.getCell('F3').value='Win Rate'; summary.getCell('G3').value='Net PnL'; summary.getCell('H3').value='Avg Discipline'; ['D3','E3','F3','G3','H3'].forEach((ref) => { const cell=summary.getCell(ref); cell.font={bold:true,color:{argb:white}}; cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:navy}}; });
    const setups = [...new Set(rows.map((row) => row.setup).filter(Boolean))].slice(0, 30); setups.forEach((setup,index) => { const row=4+index; summary.getCell(`D${row}`).value=setup; summary.getCell(`E${row}`).value={formula:`COUNTIF('Raw Trade Data'!F4:F${last},D${row})`}; summary.getCell(`F${row}`).value={formula:`IFERROR(COUNTIFS('Raw Trade Data'!F4:F${last},D${row},'Raw Trade Data'!K4:K${last},">0")/E${row},0)`}; summary.getCell(`G${row}`).value={formula:`SUMIF('Raw Trade Data'!F4:F${last},D${row},'Raw Trade Data'!K4:K${last})`}; summary.getCell(`H${row}`).value={formula:`IFERROR(AVERAGEIF('Raw Trade Data'!F4:F${last},D${row},'Raw Trade Data'!Q4:Q${last}),0)`}; summary.getCell(`F${row}`).numFmt='0.0%'; summary.getCell(`G${row}`).numFmt='$#,##0.00;[Red]-$#,##0.00'; });
    summary.columns = [{width:24},{width:18},{width:3},{width:28},{width:12},{width:14},{width:16},{width:18}]; summary.getCell('A10').value='Data source'; summary.getCell('B10').value='STRUM owner-scoped Supabase export'; summary.getCell('A11').value='Market enrichment'; summary.getCell('B11').value='Finnhub / Polygon when available';
    [raw, insights, summary].forEach((sheet) => { sheet.properties.defaultRowHeight = 18; sheet.eachRow((row) => row.eachCell((cell) => { cell.border = { bottom:{ style:'hair', color:{argb:'D6DFEA'} } }; })); });
    return workbook;
}

export async function tradingWorkbookBuffer(data) { return buildTradingWorkbook(data).then((workbook) => workbook.xlsx.writeBuffer()); }
